services:
  - name: admin2
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - path: /
        port: 3000
  - name: api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - path: /
        port: 8000
  - name: client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - path: /
        port: 3001
